# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod.name=Clearviews
mod.id=clearviews
mod.version=2.0.4
mod.group=dev.bikerboys.clearviews
mod.description=removes the annoying blindness/nausea/darkness effects and removes overlays like water fog, pumpkin, spyglass, portal overlay etc. Compatible with sodium and highly configurable.
mod.source=https://github.com/michiel1106/clearviews-multiloader
mod.issues=https://github.com/michiel1106/clearviews-multiloader/issues
mod.license=MIT
mod.modrinth=https://modrinth.com/mod/clearviews
mod.curseforge=https://www.curseforge.com/minecraft/mc-mods/clearviews
mod.kofi=https://ko-fi.com/bikerboys
mod.discord=https://discord.gg/p6ShJPq98d

# Publishing
publish.modrinth=TwYypE5e
publish.curseforge=1132220

# Dependencies
deps.fabric_loader_version=0.16.14
deps.devauth_version=1.2.1
deps.mixinconstraints_version=1.1.0
deps.mixinsquared_version=0.2.0
deps.yacl_version=3.7.1

# Build Plugins
# in libs.versions.toml

# Minecraft properties
mod.mc_dep=[VERSIONED]
mod.mc_version=[VERSIONED]

# Versioned
deps.parchment_version=[VERSIONED]
deps.fabric_api_version=[VERSIONED]
deps.modmenu_version=[VERSIONED]
deps.neoforge_version=[VERSIONED]
